### ISSUE TITLE
Improve handling of importing a project with multiple vernacular writing systems

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/TheCombine#2101]
Currently, a user must choose a single vernacular writing system for their project, and the language tag for that writing system is automatically applied to all new word. When a project is imported, if a word has multiple vernacular writing systems in use, just the first one on the list is selected for import and the rest are ignored.

**Comment by imnasnainaec** [comment]
Related: #1336

**Comment by jasonleenaylor** [comment]
In order to support multiple languages in the vernacular we will need to make a model change and have a migration path for existing projects. This change will have widespread (but predictable) affects throughout the codebase.

We already modelled this for Analysis fields, Note, Definition, Gloss, recording the language and the text, and storing a collection of them in the Sense.
