### ISSUE TITLE
Some suggestions in goal timeline are shown more than once

### ISSUE THREAD

**Issue by tyasw** [sillsdev/TheCombine#256]
Some of the suggestions in goal timeline appear twice. I don't know what is causing this.

**Comment by imnasnainaec** [comment]
The suggestion list is generated here: https://github.com/sillsdev/TheCombine/blob/master/src/components/GoalTimeline/GoalTimelineHorizontal/GoalTimelineHorizontal.tsx#L98-L112

The `Goal` interface is complicated (https://github.com/sillsdev/TheCombine/blob/master/src/types/goals.tsx#L60-L74), so there are many ways for two goals to be different and yet have identical tiles simply because they have one property the same.

**Comment by jasonleenaylor** [comment]
The intention was that there would be a discrete number of goal types. Each one should only be offered once in the choices of the next goal, but listed in the history of completed goals once for each time it was done.

**Comment by imnasnainaec** [comment]
Resolved by #559
