### ISSUE TITLE
Choose File in Project Settings is not localized

### ISSUE THREAD

**Issue by jasonleenaylor** [sillsdev/TheCombine#272]
![image](https://user-images.githubusercontent.com/2295227/62792274-8c1abf00-ba94-11e9-8929-5db7bebe74e7.png)

**Comment by imnasnainaec** [comment]
The problem is in https://github.com/sillsdev/TheCombine/blob/master/src/components/ProjectSettings/ProjectImport/ProjectImport.tsx at line 76. There is plaintext `Choose File` instead of localized text `<Translate id="________" />` except that the localization json file doesn't have anything like projectSettings.chooseFile. I could manually add an entry, but the phrase "Choose File" should probably be added at https://crowdin.com/translate/the-combine for proper translation.
