### ISSUE TITLE
Not able to undo selecting an existing sense

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#534]
[Testing Notes 6/30/2020, Current data is uneditable](https://docs.google.com/document/d/1j2jTo0xR0m5WWtVA4sq6WGPbahrqRCqVm5hgr4I7O2s/edit#)

**Comment by jasonleenaylor** [comment]
When a user selects an existing sense we create an immutable entry.
We want to change this to keep track of whether we added a semantic domain.
If a user changes one of these entries we should remove any added semdoms and create a new entry with the new info.

**Comment by jasonleenaylor** [comment]
We may want to merge the Immutable and Existing Entry and have both track the change that the user made so that it can be 'undone' we could use the word history, but that isn't completely safe because other users could have made other changes. So I think we need to track it in the ExistingEntry object. e.g. 'senseAdded', 'semDomAdded' so that they can be removed if a user changes their choice.
