### ISSUE TITLE
Docker containers need to be pruned

### ISSUE THREAD

**Issue by jmgrady** [sillsdev/TheCombine#569]
Need to create a process to periodically prune unused docker containers so that their disk usage does not grow unbounded.

**Comment by johnthagen** [comment]
We should be able to do this deterministically rather than having it be on a periodic schedule.

As mentioned in https://github.com/sillsdev/TheCombine/pull/550#issuecomment-667663656, we should just run `docker image prune --force` after we've rebuilt to remove the old dangling images. We should be able to add this as a final step in the publish playbook.

**Comment by jmgrady** [comment]
This is handled by the current CI/CD (TeamCity) outside the scope of the GitHub project.  The docker images are pruned whenever new software is built and deployed to the target servers.  There should not be any need to do it at other times.
