### ISSUE TITLE
Include Grammatical Category (Part of Speech) in Merge Duplicates word list

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/TheCombine#604]
[08/03 #11](https://docs.google.com/document/d/1qvi7sQXW800gPwsMN3WOAc4REfKR8JGliZZbc1SHBdY/edit#heading=h.a6tmena8kd4z) Include Grammatical Category (Part of Speech) in what is displayed for candidates in Merge Duplicates

There are two parts of this:
- [x] Finding a way to display it on the card without adding to the clutter. (#2245)
- [ ] When considering if two words match, the POS should probably affect the score. (Perhaps 1.5 penalty in `GetWordScore` if all parts of speech are different). (#2445)

**Comment by imnasnainaec** [comment]
Currently, this is only implemented in the backend model:
```
        /// <summary> Not implemented in frontend. </summary>
        [BsonElement("partOfSpeech")]
        public string PartOfSpeech { get; set; }
```

**Comment by jasonleenaylor** [comment]
There are two parts of this:
1. Finding a way to display it on the card without adding to the clutter. 
2. When considering if two words match, the POS should probably affect the score.

**Comment by jasonleenaylor** [comment]
Requirements for the Merge card display:
1. We want the same part of speech to look the same in different projects
2. We want the indication of part of speech to be as small as possible (tooltips can be full descriptions)


Ideas for card display:
1. Allow the POS to be dropped on smaller screen sizes
2. Use similar colors for related POS
3. Use the abbrev of the POS to create the icon (rather than pre-parsing the GoldEtic data)
4. May want to consider what to do in the sidebar (what if they are different, or if one has POS and the other doesn't)

Challenges:
1. Users can create custom categories 
2. The Lift file doesn't appear to have the unique identifiers
3. Finding unique and distinct icons for categories will be challenging
